# Generated by Django 6.1.1 on 2026-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_service_alter_contactmessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='project_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
